version: "3.8"

services:
  db:
    container_name: api-db
    image: postgres:12.2
    volumes:
      - postgres_volume:/var/lib/postgresql
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=oskar
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=rating_portal

  api:
    container_name: panel-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/testfastapi/src
      - ./tests:/home/testfastapi/tests
    depends_on:
      - db
    stdin_open: true
    environment:
      - DB_HOST=db
      - DB_PASSWORD=abc123
    tty: true
    command: bash -c "cd portal && alembic upgrade head && cd .. && 
                      uvicorn portal.main:app --host 0.0.0.0 --port 8000 --reload"


volumes:
  postgres_volume: