version: "3.8"

services:
  db:
    container_name: api-db
    image: postgres:12.2
    ports:
      - "5435:5433"
    volumes:
      - postgres_volume:/var/lib/postgresql
    env_file:
      - .env

  api:
    container_name: panel-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: bash -c "uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./tests:/tests
    depends_on:
      - db
    env_file:
      - .env
    stdin_open: true
    tty: true



volumes:
  postgres_volume:
